
title : Literate Web Font
baseurl: /literatewebfont/

pygments: true
author:
  name: bewest
  email: bewest+literatewebfonts@gmail.com
  github: bewest

#exclude: [ js, css ]
exclude: [ '*.rb', '*.py' ]

#####
# EOF
