
title : Literate Web Font

url: http://bewest.github.com/literatewebfont/
pygments: true
author:
  name: bewest
  email: bewest+literatewebfonts@gmail.com
  github: bewest

#exclude: [ js, css ]
exclude: [ '*.rb', '*.py' ]

#####
# EOF
